platform :ios, '8.0'

target "TO-DO" do
  pod 'SDAutoLayout'
  pod 'MBProgressHUD'
  pod 'TPKeyboardAvoiding'
  pod 'Masonry'
  pod 'JSONModel'
  pod 'Qiniu'
  pod 'GTMBase64'
  pod 'AVOSCloud', '~> 3.2.9'
  pod 'SDWebImage'
  pod "RTRootNavigationController"
  pod 'AutoLinearLayoutView'
  pod 'JVFloatingDrawer'
  pod 'MGSwipeTableCell'
  pod 'ZFDragableModalTransition'
  pod 'FSCalendar', :git => "https://github.com/Seanwong933/FSCalendar.git"
  pod 'MagicalRecord'
  pod 'CocoaLumberjack'
  pod 'DGActivityIndicatorView'
  pod 'AFNetworking-Synchronous'
  pod 'RealReachability'
  pod 'IGLDropDownMenu'
  pod 'NetworkEye'
  pod 'LCActionSheet'
  pod 'FDFullscreenPopGesture'
  pod 'AMap2DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  pod 'MJExtension'
  pod 'JMRoundedCorner'
  pod 'BEMCheckBox'
end